apiVersion: apps/v1
kind: Deployment
metadata:
  name: falcon
  namespace: default
  labels:
    app: falcon
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: falcon
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: falcon
    spec:
      containers:
      - image: us-docker.pkg.dev/genaiongke/falcon/testfalcon@sha256:482684d5c2f3dcf245661c4004560234574897372a469b507694be347d5de66c
        imagePullPolicy: IfNotPresent
        name: testfalcon-sha256-1
        resources:
          limits:
            nvidia.com/gpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---

apiVersion: v1
kind: Service
metadata:
  name: falcon-service
  namespace: default
  labels:
    app: falcon
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: falcon
  sessionAffinity: None
  type: LoadBalancer
